#!/bin/sh

# Generate native and web tables from the canonical knekko asset catalog.

set -eu
export LC_ALL=C

if [ "$#" -ne 4 ]; then
	echo "Usage: $0 CATALOG.tsv ASSET-DIRECTORY CPP-OUTPUT GO-OUTPUT" >&2
	exit 2
fi

catalog=$1
asset_directory=$2
cpp_output=$3
go_output=$4

[ -f "$catalog" ] && [ ! -L "$catalog" ] || {
	echo "Missing regular icon catalog: $catalog" >&2
	exit 1
}
[ -d "$asset_directory" ] && [ ! -L "$asset_directory" ] || {
	echo "Missing regular icon asset directory: $asset_directory" >&2
	exit 1
}

cpp_temporary=$(mktemp "${TMPDIR:-/tmp}/knekko-settings-icons-cpp.XXXXXX")
go_temporary=$(mktemp "${TMPDIR:-/tmp}/knekko-settings-icons-go.XXXXXX")
trap 'rm -f "$cpp_temporary" "$go_temporary"' EXIT INT TERM HUP

icons=0
while IFS="$(printf '\t')" read -r name label family size file expected_hash; do
	case $name in
		''|'#'*) continue ;;
	esac
	case $name:$label:$family:$size:$file:$expected_hash in
		gear-knekko-[0-9][0-9]:[0-9][0-9]:small:*:[0-9][0-9].png:*|\
		gear-knekko-[0-9][0-9]:[0-9][0-9]:medium:*:[0-9][0-9].png:*|\
		gear-knekko-[0-9][0-9]:[0-9][0-9]:large:*:[0-9][0-9].png:*) ;;
		*) echo "Malformed icon catalog entry: $name" >&2; exit 1 ;;
	esac
	expected_number=$(printf '%02d' "$((icons + 1))")
	[ "$name" = "gear-knekko-$expected_number" ] &&
		[ "$label" = "$expected_number" ] &&
		[ "$file" = "$expected_number.png" ] || {
		echo "Icon catalog is missing ordered entry $expected_number" >&2
		exit 1
	}
	case $size in
		''|*[!0-9]*) echo "Invalid icon size for $name" >&2; exit 1 ;;
	esac
	[ "$size" -ge 1 ] && [ "$size" -le 32 ] || {
		echo "Invalid icon size for $name" >&2
		exit 1
	}
	case $expected_hash in
		*[!0-9a-f]*|'') echo "Invalid icon hash for $name" >&2; exit 1 ;;
	esac
	[ "${#expected_hash}" -eq 64 ] || {
		echo "Invalid icon hash for $name" >&2
		exit 1
	}
	asset=$asset_directory/$file
	[ -f "$asset" ] && [ ! -L "$asset" ] || {
		echo "Missing icon asset: $asset" >&2
		exit 1
	}
	actual_hash=$(sha256sum "$asset")
	actual_hash=${actual_hash%% *}
	[ "$actual_hash" = "$expected_hash" ] || {
		echo "Icon asset hash mismatch: $asset" >&2
		exit 1
	}
	icons=$((icons + 1))
done <"$catalog"
[ "$icons" -eq 36 ] || {
	echo "Icon catalog must contain exactly 36 assets" >&2
	exit 1
}

awk -F '\t' '
	BEGIN {
		print "/* Generated by ops/deck-menu/generate-knekko-settings-icons.sh. */"
		print "const KnekkoSettingsIconDefinition kKnekkoSettingsIconDefinitions[] = {"
	}
	/^#/ { next }
	{
		printf "    {\"%s\", \"%s\", %d},\n", $1, $5, $4
	}
	END { print "};" }
' "$catalog" >"$cpp_temporary"

awk -F '\t' '
	BEGIN {
		print "package main"
		print ""
		print "// Generated by ops/deck-menu/generate-knekko-settings-icons.sh."
		print "var knekkoSettingsIconSpecs = []settingsIconSpec{"
	}
	/^#/ { next }
	{
		printf "\t{name: \"%s\", label: \"%s\", family: \"%s\", imageURL: \"/assets/settings-icons/%s\"},\n", $1, $2, $3, $5
	}
	END { print "}" }
' "$catalog" >"$go_temporary"

mkdir -p "$(dirname "$cpp_output")" "$(dirname "$go_output")"
mv "$cpp_temporary" "$cpp_output"
mv "$go_temporary" "$go_output"
trap - EXIT INT TERM HUP
