(in-package #:retrodeck)

(defun dashboard-terminal-title (launch-plan)
  (let ((label (getf launch-plan :label)))
    (check-type label string)
    (string-upcase label)))

(defun dashboard-terminal-starting-status (launch-plan)
  (format nil "STARTING ~A" (dashboard-terminal-title launch-plan)))

(defun decode-native-terminal-result (result)
  (unless (and (listp result) (= (length result) 5))
    (error "Native terminal result is invalid"))
  (destructuring-bind (started touch exit-code signal error) result
    (unless (member started '(0 1) :test #'eql)
      (error "Native terminal started flag is invalid"))
    (unless (member touch '(0 1) :test #'eql)
      (error "Native terminal touch flag is invalid"))
    (unless (or (= exit-code -1) (<= 0 exit-code 255))
      (error "Native terminal exit code is invalid"))
    (unless (or (= signal -1) (<= 1 signal 255))
      (error "Native terminal signal is invalid"))
    (when error
      (check-type error string))
    (when (and (= started 0)
               (or (= touch 1) (not (= exit-code -1)) (not (= signal -1))))
      (error "Native terminal result describes an unstarted child"))
    (when (and (not (= exit-code -1)) (not (= signal -1)))
      (error "Native terminal result has both an exit code and signal"))
    (list :started (= started 1)
          :exited-for-touch (= touch 1)
          :exit-code (unless (= exit-code -1) exit-code)
          :signal (unless (= signal -1) signal)
          :error error)))

(defun dashboard-terminal-result-status (launch-plan result)
  (let ((title (dashboard-terminal-title launch-plan))
        (error (getf result :error))
        (exit-code (getf result :exit-code))
        (signal (getf result :signal)))
    (cond
      ((and error (plusp (length error)))
       (format nil "~A ERROR - CHECK LOG" title))
      ((not (getf result :started))
       (format nil "~A DID NOT START" title))
      ((getf result :exited-for-touch)
       (format nil "RETURNED FROM ~A" title))
      ((eql exit-code 0)
       (format nil "~A EXITED" title))
      (exit-code
       (format nil "~A EXITED (STATUS ~D)" title exit-code))
      (signal
       (format nil "~A STOPPED (SIGNAL ~D)" title signal))
      (t
       (format nil "~A STOPPED" title)))))

(defun run-dashboard-terminal (launch-plan)
  (let* ((executable (getf launch-plan :executable))
         (arguments (getf launch-plan :arguments))
         (environment (getf launch-plan :environment))
         (label (getf launch-plan :label))
         (keymap (cdr (assoc "RETRO_DECK_KEYMAP" environment :test #'string=))))
    (check-type executable string)
    (check-type label string)
    (unless (and (= (length arguments) 1) (stringp (first arguments)))
      (error "Terminal launch plan needs one mode argument"))
    (check-type keymap string)
    (unless (and (getf launch-plan :touch-supervision)
                 (getf launch-plan :mirror-console))
      (error "Terminal launch plan needs touch supervision and console mirroring"))
    (finish-menu-sound)
    (let ((result
            (decode-native-terminal-result
             (run-terminal (native-path-string executable)
                           (coerce keymap 'base-string)
                           (coerce (first arguments) 'base-string)
                           (coerce label 'base-string)))))
      (let ((error (getf result :error)))
        (when (and error (plusp (length error)))
          (format *error-output* "retrodeck: ~A~%" error)))
      result)))
